name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  api:
    if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js/Playwright Test environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - run: npm run test:api

  schema:
    if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js/Playwright Test environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - run: npm run test:schema

  all:
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js/Playwright Test environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "18"
          cache: npm
      - run: npm ci
      - run: npm run test:all

      - name: Upload html reporter results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: playwright-report
          path: playwright-report

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: playwright-report
